#! /bin/bash

# This test is to be used only in container repositories in which the
# container files are generated by the distgen tool.
# This tests checks if files present in the repository are the same as
# freshly generated files.
# The commands to make freshly generated files are:
#   'make clean-versions'
#   'make generate-all'
#
# The responsibility to regenerate all the needed files lies with
# the Pull Request's author, who need to add them in a separate commit
# in the PR.

readonly ERR_DG=5

git status
make clean-versions
make generate-all
git diff --ignore-submodules=all --exit-code && exit 0

# the files are not regenerated properly
git show -s
echo "Distgen-generated files are not regenerated properly."
echo "Please regenerate them with:"
echo "'make clean-versions'"
echo "'make generate-all'"
exit $ERR_DG
