#!/bin/bash

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")"/../test-lib.sh

function ctest_npm_works() {
  ct_info "  Testing of NPM availability"
  ct_npm_works
  ct_info "  Success!"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  ct_init
  ctest_npm_works "$@"
  ct_finish
fi

# vim: set tabstop=2:shiftwidth=2:expandtab:
