#!/bin/bash

set -e

. test-lib.sh

combinations="c9s:quay.io/sclorg/postgresql-15-c9s
rhel9:registry.redhat.io/rhel9/postgresql-15
rhel10:registry.redhat.io/rhel10/postgresql-15
"

for c in $combinations; do
    public_name=$(ct_get_public_image_name "${c%%:*}" postgresql 15)
    [ "$public_name" == "${c#*:}" ]
done

echo "public_image_name test completed successfully."
