#!/bin/bash

set -e

. test-lib.sh

combinations="c9s:quay.io/c9s/postgresql-15-c9s:c9s
rhel8:registry.redhat.io/rhel8/postgresql-15
rhel9:registry.redhat.io/rhel9/postgresql-15
"

for c in $combinations; do
    public_name=$(ct_get_public_image_name "${c%%:*}" postgresql 10)
    [ "$public_name" == "${c#*:}" ]
done

echo "public_image_name test completed successfully."
