#! /bin/bash

. ./test-lib.sh


function foo_neg() {
  echo "running foo_neg"
  TESTCASE_RESULT=1
}
function bar() {
  echo "running bar"
  TESTCASE_RESULT=0
}
function foo() {
  echo "running foo"
  TESTCASE_RESULT=0
}

TEST_SET_POS="foo bar"
TEST_SET_NEG="foo_neg bar"
TESTSUITE_RESULT=0
UNSTABLE_TESTS=""
IGNORE_UNSTABLE_TESTS=0
ret_val=0

echo "running positive TC that should pass"
CID_FILE_DIR=$(mktemp -d)
TEST_SUMMARY=""
TEST_SET=${TEST_SET_POS} ct_run_tests_from_testset "should_pass" >> /dev/null
if test $TESTSUITE_RESULT -eq 0 ; then
  echo "TC has passed"
else
  echo "positive TC has failed"
  ret_val=1
fi

echo "running negative TC that should fail"
CID_FILE_DIR=$(mktemp -d)
TEST_SUMMARY=""
TEST_SET=${TEST_SET_NEG} ct_run_tests_from_testset "should_fail" >> /dev/null
if test $TESTSUITE_RESULT -eq 1 ; then
  echo "TC has failed successfuly"
else
  echo "negative TC has succeeded, which is bad"
  ret_val=1
fi
exit $ret_val
